#!/usr/bin/env bash
# This script installs nginx on a server and configures it to serve a hello world output

sudo apt install nginx -y
sudo rm /var/www/html/*.html
sudo echo "Hello World\!" > /var/www/html/index.html
sudo systemctl reload nginx
