#!/usr/bin/env bash
# This script configures a new server to redirect on a certain page request

apt update

apt install nginx -y

rm /var/www/html/*.html

echo "Hello World!" > /var/www/html/index.html

sed -i '42i\        rewrite ^/redirect_me$ / permanent;' /etc/nginx/sites-availab>

/etc/init.d/nginx restart
