#!/usr/bin/env bash
# This script configures a new server to redirect on a certain page request

sudo apt update

sudo apt install nginx -y

sudo chown -R "$USER":"$USER" /var/www/html

sudo chmod -R 755 /var/www

sudo rm /var/www/html/*.html

echo "Hello World\!" > /var/www/html/index.html

sudo sed -i '42i\        rewrite ^/redirect_me$ / permanent;' /etc/nginx/sites-available/default

sudo systemctl reload nginx
