#!/usr/bin/env bash
# This script configures a new server with a custom 404 page

apt update

apt install nginx -y

rm /var/www/html/*.html

echo "Hello World!" > /var/www/html/index.html

sed -i '42i\        rewrite ^/redirect_me$ / permanent;' /etc/nginx/sites-available/default

sed -i '43i\        error_page 404 /404.html;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/404.html

/etc/init.d/nginx restart

