#!/usr/bin/env bash
# This script installs nginx and configures it's http response to contain a custom header

sudo apt install nginx

sudo sed -i "42i\	add_header X-Served-By $(hostname);" /etc/nginx/sites-enabled/default

sudo /etc/init.d/nginx restart
