#!/usr/bin/env bash
# This displays the PID, along with the process name, of processes whose name contain the word bash

pgrep -af bash | while read -r pid cmd; do
    echo "$pid $(basename $cmd)"
done
