#!/usr/bin/env bash
# Displays a message indefinitely with a sleep of 2 between each iteration
# Responds to SIGTERM with "I am invincible!!!"

trap 'echo "I am invincible!!!"; exit' SIGTERM
i=5
while [ "$i" == "$i" ]; do
    echo "To infinity and beyond indefinitely"
    sleep 2
done

